# Generated by Django 5.2.1 on 2025-06-19 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(verbose_name=100)),
                ('descripcion', models.CharField(verbose_name=256)),
                ('stock_actual', models.IntegerField(verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(verbose_name=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(verbose_name=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.insumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
