# Generated by Django 5.2.1 on 2025-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movimiento_stock',
            name='cantidad',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='movimiento_stock',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
