# Generated by Django 5.2.1 on 2025-06-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_insumo_descripcion_alter_insumo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movimiento_stock',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
