# Generated by Django 5.2.1 on 2025-11-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_insumo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=20),
        ),
    ]
