# Generated by Django 5.2.1 on 2025-11-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_insumo_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='unidad_medida',
        ),
    ]
