# Generated by Django 5.2.1 on 2025-10-24 14:24

import pacientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('dui', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DUI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('datos_medicos', models.JSONField(blank=True, default=pacientes.models.default_datos_medicos)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nombres', 'apellidos'], name='pacientes_p_nombres_2b26b7_idx'), models.Index(fields=['telefono'], name='pacientes_p_telefon_f5fa8f_idx'), models.Index(fields=['dui'], name='pacientes_p_dui_906588_idx')],
            },
        ),
    ]
