# Generated by Django 5.2.1 on 2025-10-27 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FichaOrtodoncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta_inicial', models.TextField()),
                ('diagnostico', models.TextField()),
                ('oclusion', models.CharField(max_length=100)),
                ('mordida', models.CharField(max_length=100)),
                ('plan_tratamiento', models.TextField()),
                ('estado_tratamiento', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_ortodoncia', to='expediente.expediente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaProgresoOrto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_visita', models.TextField()),
                ('observaciones_clinicas', models.TextField()),
                ('procedimiento_realizado', models.TextField()),
                ('odontograma_snapshot', models.JSONField(blank=True, default=list)),
                ('odontograma_comentarios', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ficha_ortodoncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_progreso', to='expediente.fichaortodoncia')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='expediente.expediente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OdontogramaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='expediente.odontograma')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OdontogramaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza_numero', models.PositiveIntegerField()),
                ('cara', models.CharField(choices=[('O', 'Oclusal'), ('M', 'Mesial'), ('D', 'Distal'), ('V', 'Vestibular'), ('P', 'Palatina'), ('GLOBAL', 'Global')], max_length=7)),
                ('condicion', models.CharField(max_length=50)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='expediente.odontogramaversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['numero_expediente'], name='expediente__numero__d5058f_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['paciente'], name='expediente__pacient_ac0499_idx'),
        ),
        migrations.AddIndex(
            model_name='fichaortodoncia',
            index=models.Index(fields=['expediente'], name='expediente__expedie_324268_idx'),
        ),
        migrations.AddIndex(
            model_name='fichaortodoncia',
            index=models.Index(fields=['estado_tratamiento'], name='expediente__estado__beb1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='notaprogresoorto',
            index=models.Index(fields=['ficha_ortodoncia'], name='expediente__ficha_o_603882_idx'),
        ),
        migrations.AddIndex(
            model_name='notaprogresoorto',
            index=models.Index(fields=['created_at'], name='expediente__created_b8337e_idx'),
        ),
        migrations.AddIndex(
            model_name='odontograma',
            index=models.Index(fields=['expediente'], name='expediente__expedie_53cbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='odontogramaversion',
            index=models.Index(fields=['odontograma'], name='expediente__odontog_102a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='odontogramaversion',
            index=models.Index(fields=['created_at'], name='expediente__created_c4a9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='odontogramadetalle',
            index=models.Index(fields=['version'], name='expediente__version_9498ef_idx'),
        ),
        migrations.AddIndex(
            model_name='odontogramadetalle',
            index=models.Index(fields=['pieza_numero'], name='expediente__pieza_n_35e774_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='odontogramadetalle',
            unique_together={('version', 'pieza_numero', 'cara', 'condicion')},
        ),
    ]
