# Generated by Django 5.2.1 on 2025-11-15 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada'), ('no_asistio', 'No Asistió')], default='programada', max_length=20, verbose_name='Estado de la Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo del Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
    ]
