# Generated by Django 5.2.1 on 2025-10-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(max_length=256)),
                ('nivel_satisfaccion', models.IntegerField(default=0)),
            ],
        ),
    ]
