# Generated by Django 5.2.1 on 2025-11-15 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='preguntas_respuestas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
