# Generated by Django 5.2.1 on 2025-11-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_encuesta_fecha_encuesta_preguntas_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
